#!/usr/bin/env bash
set -euo pipefail

# Reads the gitignored root `.env` and injects its values into the iWADemo build:
#   gen-device  - bake into Examples/iWADemo/iWADemo/Generated/IWASecrets.swift
#                 (on-device builds: ProcessInfo.environment is empty there).
#   print-sim   - emit SIMCTL_CHILD_<KEY>=<value> lines for `xcrun simctl launch`.
#   export-sim  - emit `export SIMCTL_CHILD_<KEY>=...` for `eval "$(... export-sim)"`.
#
# With no `.env`, gen-device still regenerates an empty map so the demo compiles.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

ENV_FILE="${IWA_ENV_FILE:-$ROOT/.env}"
GEN_DIR="$ROOT/Examples/iWADemo/iWADemo/Generated"
GEN_FILE="$GEN_DIR/IWASecrets.swift"

WHITELIST=(SOLANA_CLUSTER SOLANA_RPC_URL HELIUS_RPC_URL WALLETCONNECT_PROJECT_ID JUP_API_URL JUP_API_KEY JUPITER_API_KEY JUP_FETCH_TIMEOUT_MS)

KEYS=()
VALUES=()

is_whitelisted() {
  local key="$1" k
  for k in "${WHITELIST[@]}"; do
    [[ "$k" == "$key" ]] && return 0
  done
  return 1
}

load_env() {
  KEYS=()
  VALUES=()
  [[ -f "$ENV_FILE" ]] || return 0
  local line key val
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    [[ -z "$line" ]] && continue
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" != *=* ]] && continue
    key="${line%%=*}"
    val="${line#*=}"
    key="${key//[[:space:]]/}"
    val="${val#"${val%%[![:space:]]*}"}"
    val="${val%"${val##*[![:space:]]}"}"
    is_whitelisted "$key" || continue
    KEYS+=("$key")
    VALUES+=("$val")
  done < "$ENV_FILE"
}

swift_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  printf '%s' "$s"
}

cmd_gen_device() {
  load_env
  mkdir -p "$GEN_DIR"
  {
    echo "// Generated by scripts/iwa-env.sh — do not edit, do not commit (gitignored)."
    echo "//"
    echo "// Baked from the gitignored root .env so on-device builds (where"
    echo "// ProcessInfo.environment is empty) can read SOLANA_RPC_URL /"
    echo "// WALLETCONNECT_PROJECT_ID etc."
    echo "enum IWASecrets {"
    if ((${#KEYS[@]} == 0)); then
      echo "    static let values: [String: String] = [:]"
    else
      echo "    static let values: [String: String] = ["
      local i
      for i in "${!KEYS[@]}"; do
        printf '        "%s": "%s",\n' "${KEYS[$i]}" "$(swift_escape "${VALUES[$i]}")"
      done
      echo "    ]"
    fi
    echo "}"
  } > "$GEN_FILE"
  echo "iwa-env: wrote $GEN_FILE (${#KEYS[@]} keys)" >&2
}

cmd_print_sim() {
  load_env
  ((${#KEYS[@]})) || return 0
  local i
  for i in "${!KEYS[@]}"; do
    printf 'SIMCTL_CHILD_%s=%s\n' "${KEYS[$i]}" "${VALUES[$i]}"
  done
}

cmd_export_sim() {
  load_env
  ((${#KEYS[@]})) || return 0
  local i
  for i in "${!KEYS[@]}"; do
    printf 'export SIMCTL_CHILD_%s=%q\n' "${KEYS[$i]}" "${VALUES[$i]}"
  done
}

usage() {
  cat <<EOF
Usage: scripts/iwa-env.sh <command>

Commands:
  gen-device   Bake .env into Examples/iWADemo/iWADemo/Generated/IWASecrets.swift.
  print-sim    Print SIMCTL_CHILD_<KEY>=<value> lines.
  export-sim   Print 'export SIMCTL_CHILD_<KEY>=...' lines for eval.

Env overrides:
  IWA_ENV_FILE=$ENV_FILE
EOF
}

case "${1:-}" in
  gen-device) cmd_gen_device ;;
  print-sim)  cmd_print_sim ;;
  export-sim) cmd_export_sim ;;
  ""|help|-h|--help) usage ;;
  *) echo "Unknown command: $1" >&2; usage >&2; exit 2 ;;
esac
